
# config/packages/parameters.yaml

parameters:
    badwords:
        - badword1
        - badword2
        - badword3

 # config/packages/parameters.yaml

parameters:
    badwords:
        - badword
        - badword1
        - badword2

