
#index:
#    path: /
#    controller: App\Controller\DefaultController::index
stats:
    path: /stats
    controller: App\Controller\EventController::statistiques
    
calendar:
    path: /calendar
    controller: App\Controller\EventController::calendar   

    

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

