#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_cart_buy_all:
    path: /cart/buy_all
    controller: App\Controller\CartController::buyAll
    methods: ['POST']

generate_pdf:
    path: /generate-pdf
    controller: App\Controller\CartController::generatePdf
